branch-defaults:
  default:
    environment: udagram-grace-project-dev
    group_suffix: null
environment-defaults:
  udagram-grace-project-dev:
    branch: null
    repository: null
global:
  application_name: udagram-grace-project
  branch: null
  default_ec2_keyname: udagramKey
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
